obama-imd/obama

.github/pull_request_template.md
build.gradle
src/main/kotlin/br/ufrn/imd/obama/oa/domain/gateway/TemaConteudoDatabaseGateway.kt
src/main/kotlin/br/ufrn/imd/obama/oa/domain/model/Curriculo.kt
src/main/kotlin/br/ufrn/imd/obama/oa/domain/usecase/TemaConteudoUseCase.kt
src/main/kotlin/br/ufrn/imd/obama/oa/domain/usecase/TemaConteudoUseCaseImpl.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/adapter/TemaConteudoDatabaseGatewayAdapter.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/configuration/CaffeineConfig.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/entity/TemaConteudoEntity.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/mapper/CurriculoMapper.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/mapper/DescritorMapper.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/mapper/DisciplinaMapper.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/mapper/NivelEnsinoMappper.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/mapper/ObjetoAprendizagemMapper.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/mapper/TemaConteudoMapper.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/mapper/TipoLicensaUsoMapperEntity.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/repository/TemaConteudoRepository.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/NivelEnsinoResourceImpl.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/TemaConteudoResource.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/TemaConteudoResourceImpl.kt
src/main/resources/application.yml
src/test/kotlin/br/ufrn/imd/obama/oa/domain/usecase/DescritorUseCaseImplTest.kt
src/test/kotlin/br/ufrn/imd/obama/oa/domain/usecase/TemaConteudoUseCaseImplTest.kt
src/test/kotlin/br/ufrn/imd/obama/oa/infrastructure/adapter/BNCCObjetoAprendizagemDatabaseGatewayAdapterTest.kt
src/test/kotlin/br/ufrn/imd/obama/oa/infrastructure/adapter/DescritorDatabaseGatewayAdapterTest.kt
src/test/kotlin/br/ufrn/imd/obama/oa/infrastructure/adapter/NivelEnsinoDatabaseGatewayAdapterTest.kt
src/test/kotlin/br/ufrn/imd/obama/oa/infrastructure/adapter/TemaConteudoDatabaseGatewayAdapterTest.kt
src/test/kotlin/br/ufrn/imd/obama/oa/infrastructure/resource/TemaConteudoResourceImplTest.kt

Adiciona o cache para melhorar perfomace da listagem de niveis de ensino e tema conteúdo
- Configurado um cache em memória
- Adicionado cache na rota que lista nivel de ensino
- Adicionado cache na rota que lista tema contéudo

Adiciona o cache na rota que lista nivel de ensino e tema contéudo

---

src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/configuration/SecurityConfiguration.kt
src/main/resources/application-local.yml

Altera as rotas bloqueadas pelo security filter

---

src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/configuration/SecurityConfiguration.kt

Desfaz o bloqueio geral

---

src/main/resources/db/migration/V12__inserir_habilidade.sql

OB-0035: Corrige script que insere as habilidades

---

src/main/kotlin/br/ufrn/imd/obama/planoaula/infrastructure/resource/PlanoAulaResourceImpl.kt
src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/configuration/SecurityConfiguration.kt
src/test/kotlin/br/ufrn/imd/obama/planoaula/infrastructure/resource/PlanoAulaResourceImplTest.kt

Teve um erro/bug por causa do nome da branch estar em minúsculo, acabei criando outra branch. Objetivo da PR é juntar tudo de novo.
Correção do path do endpoint e de nome de um teste.

Feature: ob-0021 <- OB-0021

---

README.md
src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/annotation/PasswordConstraintValidator.kt
src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/annotation/ValidPassword.kt
src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/resource/exchange/CadastrarUsuarioRequest.kt
src/test/kotlin/br/ufrn/imd/obama/usuario/infrastructure/resource/UsuarioResourceImplTest.kt
src/test/kotlin/br/ufrn/imd/obama/usuario/util/UsuarioDatabaseUtil.kt

Feature/OB-0034: Adiciona validação para que novos usuários se cadastra com senhas mais fortes

---

.gitignore
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/adapter/ObjetoAprendizagemDatabaseGatewayAdapter.kt
src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/repository/ObjetoAprendizagemRepository.kt
src/test/kotlin/br/ufrn/imd/obama/oa/infrastructure/adapter/ObjetoAprendizagemDatabaseGatewayAdapterTest.kt

OB-0037: Corrige teste e adiciona .idea/ no .ignore

---

src/main/kotlin/br/ufrn/imd/obama/oa/infrastructure/repository/ObjetoAprendizagemRepository.kt

Resolvendo bug do buscar OA's no banco de dados postrgresql

---

src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/adapter/EmailGatewayAdapter.kt
src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/configuration/UsuarioConfig.kt

Erro de compilação na main
* Muda tipo de parametro: BCryptPasswordEncoder -> PasswordEnconder
* Adiciona @Primary em email bean

Fix: Erros de bean em UsuarioConfig.kt

---

src/main/kotlin/br/ufrn/imd/obama/planoaula/domain/exception/PlanoAulaNaoEncontradoException.kt
src/main/kotlin/br/ufrn/imd/obama/planoaula/domain/gateway/PlanoAulaGateway.kt
src/main/kotlin/br/ufrn/imd/obama/planoaula/domain/usecase/PlanoAulaUseCase.kt
src/main/kotlin/br/ufrn/imd/obama/planoaula/domain/usecase/PlanoAulaUseCaseImpl.kt
src/main/kotlin/br/ufrn/imd/obama/planoaula/infrastructure/adapter/PlanoAulaGatewayAdapter.kt
src/main/kotlin/br/ufrn/imd/obama/planoaula/infrastructure/exception/PlanoAulaNaoEncontradoException.kt
src/main/kotlin/br/ufrn/imd/obama/planoaula/infrastructure/handler/PlanoAulaNaoEncontradoExceptionHandler.kt
src/main/kotlin/br/ufrn/imd/obama/planoaula/infrastructure/mapper/PlanoAulaMapper.kt
src/main/kotlin/br/ufrn/imd/obama/planoaula/infrastructure/repository/PlanoAulaRepository.kt
src/main/kotlin/br/ufrn/imd/obama/planoaula/infrastructure/resource/PlanoAulaResource.kt
src/main/kotlin/br/ufrn/imd/obama/planoaula/infrastructure/resource/PlanoAulaResourceImpl.kt
src/main/kotlin/br/ufrn/imd/obama/planoaula/infrastructure/resource/exchange/PlanoAulaBuscarPorIdResponse.kt
src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/configuration/SecurityConfiguration.kt
src/test/kotlin/br/ufrn/imd/obama/planoaula/domain/usecase/PlanoAulaUseCaseImplTest.kt
src/test/kotlin/br/ufrn/imd/obama/planoaula/infrastructure/adapter/PlanoAulaGatewayAdapterTest.kt

#48 
Criação do endpoint para buscar plano de aula por id
teste end-to-end do resource, não foi feito pois ainda não sabemos como mockar o jwt para a autenticação.

Feature/OB-0019: Buscar PlanoAula por ID

---

Jenksfile

Adiciona o jenkinsfile

---

Jenksfile

Adiciona escrita do .env no Jenkisfile

---

Jenksfile

Adiciona declaração das variáveis de ambiente

---

docker-compose.yml

Altera o docker-compose

---

Jenkinsfile

Adiciona permissão de execução do gradle pelo sh do Jenkinsfile

---

Jenkinsfile

Altera jenkinsfile

---

Jenkinsfile

Corrige acesso as credenciais do Jenkinsfile

---

Jenkinsfile

Corrige a execução do docker

---

src/main/kotlin/br/ufrn/imd/obama/planoaula/infrastructure/entity/PlanoAulaEntity.kt
src/main/kotlin/br/ufrn/imd/obama/usuario/infrastructure/entity/UsuarioEntity.kt
src/main/resources/db/migration/V15__inserir_campo_datas.sql

Adicionar novos campos necessários para controle de data de cadastro e data de atualização das tabelas usuário e plano de aula.
Adicionar novos campos necessários para controle de data de cadastro e data de atualização das tabelas usuário e plano de aula.

Adiciona campos relacionados a data de cadastro

---

src/main/resources/db/migration/V17__remove_constraints_token_plano_aula.sql
src/test/kotlin/br/ufrn/imd/obama/planoaula/domain/usecase/PlanoAulaUseCaseImplTest.kt
src/test/kotlin/br/ufrn/imd/obama/planoaula/infrastructure/adapter/PlanoAulaGatewayAdapterTest.kt

OB-0041: Remove constraints da tabela plano de aula
